const texts = [
  '\tThe Maldives is an archipelago in the Indian Ocean made up of 1,190 islands, 200 of which are inhabited. It’s a popular vacation and honeymoon destination, and it’s well known for its turquoise waters and pristine beaches. When traveling to the Maldives, choose to stay on a resort island for a relaxing and picturesque experience, or visit some of the islands inhabited by native Maldivians for a less expensive vacationing option. From snorkeling with bountiful marine life to island hopping, there is plenty to do and enjoy!\n 1. Visit the Maldives from November to April for the best weather.These months make up the dry season in the Maldives, which means the chance for rain interrupting your afternoon at the beach is much lower than during the wet season.Expect to pay more for accommodations and be around more people, as these are the most popular months to travel here.\n2. Arrange to go from May to October for less expensive lodgings.If you are looking for accommodations that are a little more wallet friendly and don’t mind a little rain, book your trip during the wet season months.This is also a great time to travel if you’d prefer a less crowded vacation, as the peak travel time to the Maldives is from November to April.\n3. Obtain a valid passport.If you don’t already have one, fill out a passport application several months before your trip.When you book your flight to the Maldives, you’ll be issued a 30 - day visa automatically.If you want, you can extend that to a 90 - day visa, depending on your travel plans',
  'Setting out to increase your talents and abilities in multiple disciplines is an audacious endeavor. It’s also very feasible to accomplish. In fact, it’s far easier to become talented in multiple areas than you may expect. Practicing the skills you wish to improve upon, maintaining a positive mindset, and broadening your base of interest and knowledge can all help you be talented in all sorts of ways.\n 1. Practice.Whatever it is you’re trying to be talented at, you know you have to practice.This is especially true if you hope to be talented in multiple areas.Fortunately, you may not need to practice quite as much as you think, and can likely make the time to practice multiple skills every day.In order to get the most out of the time you put in, you have to focus on what you’re hoping to learn.\n 2. Deconstruct the talents you hope to acquire.In order to practice deliberately and efficiently, you need to make sure you are absolutely focused during practice.One way to help maximize the efficiency of your practice time is to deconstruct the talents you hope to improve upon into specific skills.\n 3. Practice until you can self - correct.Practice enough so that you are able to both notice and correct errors in your execution of a particular ability. (Once you’ve completed a disciplined practice routine, during which you practice almost daily for a month, you will likely reach this point.)\n 4. Be consistent and persistent.Dabbling and practicing are different things.Jogging or painting twice a week are fun and healthy things to do, but in order to acquire talent, you need to be more disciplined in your pursuit of improvement.Something that may help you be persistent is choosing two very different talents to practice and improve upon during the same time period.',
  'Spending money on movies, TV, and special events can cost you a surprising amount over time. The average family spends around thousands per year on entertainment, a number that can be greatly reduced by budgeting.[1] Whether you\'re trying to budget at home or while traveling, you can reduce your entertainment expenses if you know where to cut back.Keep track of your budgeting and compare one month from another to see how your spending habits change.\n 1. Purchase a cable alternative.The first step to reducing at - home entertainment costs is ditching cable TV.Instead, choose an online streaming service.Subscribing to one of these companies can give you access to hundreds of movies, TV, and original content for usually lower cost per month.Review your most recent cable bills and find a streaming service with a lower monthly fee.\n 2. Listen to music via streaming services.Instead of purchasing every song you listen to, try a music streaming service.Most services operate as an online library filled with songs that users can hear without downloading.Although these services often have an ad - free subscription for a low cost, many also offer free options.\n 3. Acquire a library card.Whether you\'re a bookworm or a casual reader, a library card can save you hundreds on at-home entertainment. Books (paper, audio, or electronic), movies, magazines, newspapers, and music are all available for free or a minimal annual fee. Some libraries even rent out video games or hobby supplies (like cooking tools or board games).\n 4. Rent video games instead of buying them.You don\'t have to shell out your paycheck to get the latest game release; opt for a game rental service to play at a reduced cost. This option is especially ideal if you tend not to replay games and want to avoid reselling for less than the game is worth.',
  'The arts allow people to publicly express themselves in fun, creative, and meaningful ways. Art, music, and theatre all provide countless creators, musicians, and entertainers with a livelihood. Without public support and proper funding, though, these mediums may begin fading from local communities. You can help support the arts by providing financial assistance, attending community functions, and petitioning officials from your school and government.\n 1. Donate money to national arts organizations to help on a big scale.Creative projects need funding to support the cost of various supplies, tools, instruments, and other production expenses.[1] If you want to provide support on a broader level, consider donating to a national organization that supports the arts, such as the District of Columbia Commission on Arts and Humanities or the National Assembly of State Arts Agencies.[2] Check an organization’s website to see how you can donate, or give money electronically through a federal site here: https://www.pay.gov/public/form/start/973840 \n 2. Sponsor a content creator to help them get noticed.Give money on a regular basis to support specific artists, musicians, and other creative individuals.Talent can only get a person so far, but funding and recognition can help content creators to make a living. Sites like Patreon and IndieSponsor allow you to financially support artists from all over the world by providing a monthly donation.\n 3. Pledge money to local art centers and theatres.Conduct a search online to see if there are any community theatres or local art centers near your location.Even if you can’t attend the shows or productions on a regular basis, you can usually donate online. Pledging money locally allows you to see your donation in action, which isn’t as feasible when you donate to a national organization.\n 4. Give money to local street musicians and artists.Donate to a street performer or artist to help support them financially.If you don’t have cash on your person, ask to see if you can support them via digital apps like PayPal or Venmo.Some performers may also have devices that let you tip via credit/debit card. \n 5. Purchase merchandise from artists.Buy paintings, tickets, and other goods that directly fund an artist or content creator.When you purchase something from an artist, you can physically see where your money is going.If you’re not interested in sponsorships, investing your time and money into buying physical items and performance tickets can help to support the arts.',
  'Come on, it\'s Ulysses.Considered by many to be the second hardest book in the English language(mostly because the hardest book in the English language requires a working knowledge of 8 other languages to read), reading Ulysses is both enjoyable and provocative.Despite its reputation, it\'s not too difficult to read.\n 1. Understand Ulysses.Before learning how to read Ulysses, you have to know what you\'re getting into. Ulysses comprises 18 "Episodes". Each of these episodes was serialized separately, and each one reads completely differently. For example, Episode 14 parodies all of the great authors of the English language, going from Chaucer to Dickens, and Episode 18 is a lengthy monologue of about 10,000 words that comprises two giant run-on sentences. Every Episode reads like a completely different book, and therein lies the beauty of Ulysses.\n 2. Don\'t use a guidebook. When doing a formal, academic study of Ulysses, you should buy some form of guidebook. These books are about four hundred pages thick and explain Ulysses line by line. This is good because Ulysses is full of esoteric puns and references, and the guidebooks explain it all. However, switching from guidebook to guidebook over and over is very annoying. The best way to read Ulysses, if you\'re trying to read it for fun, is to just dive right in, saving all of those guidebooks for a college course.\n 3. Understand that it\'s funny. No, really, this 700 page text is hilarious. The entire idea of the novel is that Joyce is taking the epic heroes of The Odyssey and turning them into these pathetic Dubliners. The end of Episode 4 features a ten page poop joke written in the same elevated language as The Odyssey. Understanding that every sentence has some form of joke in it, be it some esoteric reference to literature or a subtle pun, turns Ulysses into a very intelligent comedy \n 4. You\'re not going to understand everything. But that\'s mostly because Joyce designed it that way.Part of the joke is that you\'re not going to get everything, and there\'s humor in that.Laugh whenever you don\'t get something, because you\'ve just walked into one of the most brilliant practical jokes in literature.',
  'Cosplay wigs are worn to make your intended character come to life. Most cosplay wigs are high-quality works of art intended for wear with the same costume for years at a time. Wearing a cosplay wig properly is as simple as remembering to put on a wig cap, putting the wig on properly, and pinning it in place.\n 1. Make sure the wig is the right size for your head.You may have already figured out if the wig is the right size for your head, and if that’s the case, you can skip to the next step.If not, quickly measure your head with measuring tape.If your head is between 21 to 22 inches(51 to 55 cm), then you should be able to fit into most cosplay wigs.If your head is any larger, it’s a good idea to try on the wig to make sure it fits comfortably.\n 2. Choose a wig cap.There are usually two types of wig caps.One kind of wig cap is made of a fishnet - like material.The other type is similar to pantyhose.The fishnet wig cap is often tighter and hair can come out of the holes.The pantyhose wig cap is usually preferred because it’s not as tight and covers all of your hair.\n 3. Arrange your hair for the wig cap.If it\'s long enough, twist your hair into a ponytail at the nape of your neck. Then, flip that ponytail so that it lies up against your head, and the tail points toward or across your forehead. If your hair is short, pin it down with hair pins so that it fits easily into the wig cap.\n 4. Pull the wig cap on.The wig cap usually won’t have a specified front or back.Start pulling on the cap from the back of your head if you have a lot of hair in a ponytail.Stuff as much of your hair as possible down toward the back of your neck, making sure it\'s still contained by the wig cap. If you have short hair or are bald, simply pull the wig cap on. Check to make sure all or most of your hair has been hidden by the cap. \n 5. Secure the wig cap with snap clips.You will need about 10 snap clips in total.Use 6 snap clips spaced evenly around the front of your head.Snap in 4 clips towards the back of your head.You can use more or less clips if necessary.',
  'Having a good stage presence is crucial to creating an engaging and lasting performance. While talent and practice are of course essential to any creative performance, nervous body language or unbelievable vocal patterns can kill the energy on stage. Whatever the performance medium, from music to acting to dancing, good stage presence gives the crowd the impression that you are in control and having fun. Most importantly, developing confidence in both your art and your ability to be a good performer will keep the crowd excited and energized throughout the show, and leave them wanting more.\n 1. Take every opportunity to practice that you get.Practice will make you feel confident at a big show, and the more venues you get to play in, the better.Practice alone at home, practice with your band, practice in front of the mirror, play for your mom, your friends, anyone who will listen.The more practice, the less of chance you’ll mess up when it counts.\n 2. Find your inner rock star.No matter what kind of performance you’re involved in, from theater to music to dance, the most important trait to have on stage is confidence.Even if you’re a bit more reserved in real life, on stage, let yourself become passionate and energetic.\n 3. Learn from the greats.Watch and attend performances of bands, actors, or dances that you idolize.See what kinds of tricks and riffs musicians use on stage, and mimic some of their best techniques.Study the behaviors of actors and dancers that captivate audiences, and adopt their body language.Remember, the point isn’t to steal what’s already been done, but to learn from past successes and synthesize what works well with your own unique sound and image.\n 4. Record your performances.This is the best way to gain a sense of what’s working when you’re on stage.For best results, film yourself rehearsing, and look for strengths and weaknesses.Does your style look natural, or are your movements forced ? Are your sound and body language clear ? Ideally, you should be able to smooth out the weak parts of your performances before even getting on stage.',
  'If you are an aspiring musician, actor, or other entertainer, at some point in your career you will need to hire an agent. Your agent will help you build on the work you have already done to book more and better jobs, helping your rise in the field. An agent will also do important paperwork like contracts, so you’ll have more time for perfecting your craft. As you can imagine, finding and hiring an agent is an important decision, and you’ll need to be prepared.\n 1. Figure out what you want to do.The point of having an agent is having a professional to help you grow your career.The best agents will be the people who can support what you want to do, but the only way they can do that is if you have a clear sense of the kind of work you want to do.\n 2. Take a headshot.Most agents will need to see a standard headshot, an 8x10 black and white glossy photograph, with your resume.Get one professionally done, and make sure your resume is attached to the back.\n 3. Create an online presence.A personal website is a good way for agents to follow up on your resume, and provide more information beyond what fits in your cover letter.Include your resume, references, contact information, and additional images or multimedia where appropriate.[5] This is also good for publicizing yourself even without your agent’s help, which is important for growing your career.\n 4. Get referrals.Referrals, that is information from other clients or people in the industry, are a common way for agents to choose clients. As you try out for and take various jobs, use that as a way to meet people and build your network.\n 5. Stay busy.Just like you will shop for agents, agents are shopping for you.If you haven’t done a lot of work, it will be hard for an agent to see you as someone who will bring business.Beyond jobs, you’ll also want to be doing other kinds of lessons and workshops in your field to show your dedication to improving.',
  'It\'s true, babies do it, and well.But clapping is more diverse than you might think.Is it appropriate to clap your hands after the allegro passage in a Mozart concerto ? What about after a sermon in church ? And what\'s the deal with snapping at a poetry reading? Learn to clap the right way.\n 1. Do the basic clap.Open your hands and clap your palms against each other, with the fingers held up towards the sky.Do it hard enough to get a good loud smacking sound out of it, but not so hard you turn your hand red.\n 2. Do the royalty clap.You know when the Queen comes out of the castle and deigns to applaud her loyal subjects with a brief applause ? That\'s what you\'re going for.A demure clap can be done just by clapping with the first two fingers, tapping them into your palm.It should make very little noise, giving the impression that you\'re clapping more than actually contributing to the group.\n 3. Clap without your hands.Not all cultures or situations call for hand on hand clapping.Learn to use other types of claps so you\'ll be prepared to celebrate in all situations.\n 4. Clap silently.In situations in which it’s inappropriate to made noise, or when the audience is primarily hearing - impaired or deaf, the general way of clapping is to raise your hands with your palms facing away from you, and to wiggle your fingers.\n 5. Do the slow clap.A slow clap starts and builds gradually into a roar of applause.To start a slow clap, begin clapping no more than once every two seconds and gradually wait for others to build and join in with you.Gradually, speed up.',
  'The classic image of a knight is a soldier who fights the enemies of his lord and king on horseback while upholding the principles of chivalry. Knighthood is thought to date back to the Ordem Equestre, horse-riding nobles of ancient Rome. and other places.[1] The image of the knight, however, comes from the “Song of Roland” and other legends of Charlemagne and his paladins, which spread from France to England with the Norman conquest of 1066. Historically, knighthood could be earned by only a select class of people, but in the last century, several modern ways have arisen to become a knight.\n 1. Be born into the noble class.In the feudal era, the opportunity to become a knight was, in practice, restricted to the nobility, as it was they who usually had the wealth necessary to own and maintain the horse, armor, and weapons that knights needed to defend their lords’ lands.\n 2. Be born male.While in modern times, both men and women can be knighted, historically only men were knighted as a matter of course.In fact, the word “knight” derives from the Anglo - Saxon word “cniht, ” meaning “boy.”[4] There were exceptions, however.\n 3. Learn from your parents what it means to be a knight.For the first seven years of his life, a boy would learn the manners required of a knight from his parents, who told him stories of chivalrous deeds and took him to tournaments.Play time involved taking up a wooden sword and shield against imagined enemies of the liege lord.\n 4. Become a page.At age 7, a boy would become a page(also called a varlet, meaning “little vassal”) in the service of a noble and any ladies of the court who resided under the noble’s roof.He would be dressed in the lord’s colors and placed under the older pages in the lord’s service.As a page, his service would be divided among household duties, physical activities, and education.\n 5. Become a squire.Usually at age 14, but sometimes as young as age 10, a page would be apprenticed to a specific knight as his armiger or squire, from the French “escuyer” for “shield bearer.” In this role, the knight -in -training was regarded as a young man and so had greater duties, responsibilities, and expectations than when he was a page.\n 6. Be invested as a knight.Assuming the squire showed himself worthy of his lessons, at age 21, he would be dubbed a knight. (In some cases, such as particular valor in combat, he might receive the honor sooner, much as battlefield promotions are accorded today, and with only a brief ritual dubbing.)',
  'It’s fun to read for pleasure but sometimes you don’t have the ability to choose how much time you get to read a book. If you need to read a book and only have 2 or 3 hours to do so, you can still get through it with some good preparation ahead of time. As you’ll see, preparing to read quickly is just as important as reading itself.\n 1. Look at the text ahead of time.First, look at the table of contents.Take note of how many chapters or sections there are and how many pages are in each.Flip through the book and take notes of charts, pictures, or subsections.Take a stab at what the book will cover ahead of time, this will assist with “active reading” later.\n 2. Calculate how long you should spend on each section.For example, If there are fifteen chapters and you have three hours, you should divide 180(60 minutes x 3) by fifteen.In this example, each chapter will take, on average, 12 minutes.Whatever the amount of time you calculate, this is not a hard and fast time, it is just a tool to help you keep track of your time and progress.You need to factor in times for breaks and also understand that some chapters will take longer amount of time and some will take a shorter amount of time to complete. \n 3. Review what your goals are.Knowing your goals will help you pay attention to the right things and not waste time on irrelevant aspects of the book.[2][3] Are you going to be quizzed on the material ? Are you trying to learn a specific skill from the pages ? Are you supposed to be paying attention to certain aspects of the book(a character, the way the author uses language, etc.) ? Knowing exactly what you need to get out of the reading will help you focus on what’s important and not waste time reading and retaining something immaterial to your goal.'
]
const titles = [
  'How to Go to the Maldives',
  'How to Be Talented in Multiple Areas',
  'How to Reduce Entertainment Expenses',
  'How to Support the Arts',
  'How to Read Ulysses',
  'How to Wear a Cosplay Wig',
  'How to Have a Good Stage Presence',
  'How to Get a Talent Agent',
  'How to Clap Your Hands',
  'How to Be a Knight',
  'How to Read a Long Chapter Book in Two or Three Hours'
]

Page({
  onShareAppMessage() {
    return {
      title: 'text',
      path: 'page/lenglish/pages/demo/demo'
    }
  },

  data: {
    title: '',
    text: '',
    idx: 0,
  },
  extraLine: [],

  onLoad(option) {
    let idx = option.index
    if(!idx){
      idx = 0
    }
    this.setData({
      title: titles[idx],
      text: texts[idx],
      idx: idx
    })
  }
})
